# --- !Ups

ALTER TABLE "CREDITS_2" ADD "BASE_ASS" VARCHAR(3) DEFAULT 'CI' NOT NULL;
ALTER TABLE "CREDITS_2" ADD "TAUX_ASS" NUMERIC DEFAULT 0 NOT NULL;

# --- !Downs

ALTER TABLE "CREDITS_2" DROP "BASE_ASS";
ALTER TABLE "CREDITS_2" DROP "TAUX_ASS";
