# --- !Ups

create table "USERS_BIS" ("ID" BIGSERIAL PRIMARY KEY,"FIRSTNAME" VARCHAR,"LASTNAME" VARCHAR,"FULLNAME" VARCHAR,"EMAIL" VARCHAR,"AVATAR_URL" VARCHAR,"IS_ADMIN" BOOLEAN DEFAULT FALSE NOT NULL,"CREATION_DATE" TIMESTAMP DEFAULT NOW() NOT NULL);
create table "LOGIN_INFO" ("ID" BIGSERIAL PRIMARY KEY,"PROVIDER_ID" VARCHAR NOT NULL,"PROVIDER_KEY" VARCHAR NOT NULL);
create table "USER_LOGIN_INFO" ("USER_ID" BIGINT NOT NULL,"LOGIN_INFO_ID" BIGINT NOT NULL);
create table "PASSWORD_INFO" ("HASHER" VARCHAR NOT NULL,"PASSWORD" VARCHAR NOT NULL,"SALT" VARCHAR,"LOGIN_INFO_ID" BIGINT NOT NULL);
create table "OAUTH1_INFO" ("ID" BIGSERIAL PRIMARY KEY,"TOKEN" VARCHAR NOT NULL,"SECRET" VARCHAR NOT NULL,"LOGIN_INFO_ID" BIGINT NOT NULL);
create table "OAUTH2_INFO" ("ID" BIGSERIAL PRIMARY KEY,"ACCESS_TOKEN" VARCHAR NOT NULL,"TOKEN_TYPE" VARCHAR,"EXPIRES_IN" INTEGER,"REFRESH_TOKEN" VARCHAR,"LOGIN_INFO_ID" BIGINT NOT NULL);
create table "OPENID_INFO" ("ID" VARCHAR NOT NULL PRIMARY KEY,"LOGIN_INFO_ID" BIGINT NOT NULL);
create table "OPENID_ATTRIBUTES" ("ID" VARCHAR NOT NULL,"KEY" VARCHAR NOT NULL,"VALUE" VARCHAR NOT NULL);


# --- !Downs

drop table "OPENID_ATTRIBUTES";
drop table "OPENID_INFO";
drop table "OAUTH2_INFO";
drop table "OAUTH1_INFO";
drop table "PASSWORD_INFO";
drop table "USER_LOGIN_INFO";
drop table "LOGIN_INFO";
drop table "USERS_BIS";